spring:
  datasource:
    url: jdbc:mysql://47.97.207.96:3306/shopping?characterEncoding=UTF-8&useSSL=false
    username: shopping
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.example.shopping.entity
